# Generated by Django 5.1.1 on 2025-01-15 15:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Mailing",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("message", models.TextField(max_length=1024, verbose_name="название")),
                (
                    "delay",
                    models.IntegerField(
                        choices=[(0, 0), (1, 1), (2, 2)],
                        verbose_name="задержка отправки",
                    ),
                ),
            ],
            options={
                "verbose_name": "Почтовое сообщение",
                "verbose_name_plural": "Почтовые сообщения",
            },
        ),
        migrations.CreateModel(
            name="Mail",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("mail", models.CharField(max_length=150, verbose_name="почта")),
                (
                    "mailing_id",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="mailing.mailing",
                        verbose_name="рассылка",
                    ),
                ),
            ],
            options={
                "verbose_name": "Почта пользователя",
                "verbose_name_plural": "Почты пользователей",
            },
        ),
        migrations.CreateModel(
            name="Telegram",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("user_id", models.CharField(max_length=11, verbose_name="id")),
                (
                    "mailing_id",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="mailing.mailing",
                        verbose_name="рассылка",
                    ),
                ),
            ],
            options={
                "verbose_name": "Телеграм-пользователь",
                "verbose_name_plural": "Телеграм-пользователи",
            },
        ),
    ]
