# Generated by Django 5.1.1 on 2025-01-15 21:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("mailing", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="mail",
            old_name="mail",
            new_name="recepient",
        ),
        migrations.RenameField(
            model_name="telegram",
            old_name="user_id",
            new_name="recepient",
        ),
    ]
