# Generated by Django 5.1.1 on 2025-01-17 12:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("mailing", "0002_rename_mail_mail_recepient_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="Logs",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "message",
                    models.TextField(
                        blank=True, max_length=1024, null=True, verbose_name="сообщение"
                    ),
                ),
                (
                    "sending_time",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="время отправки сообщения"
                    ),
                ),
                (
                    "recepient",
                    models.TextField(
                        blank=True,
                        max_length=1024,
                        null=True,
                        verbose_name="получатель",
                    ),
                ),
                (
                    "server_response",
                    models.TextField(
                        blank=True,
                        max_length=1024,
                        null=True,
                        verbose_name="ответ сервера",
                    ),
                ),
            ],
            options={
                "verbose_name": "Лог отправки",
                "verbose_name_plural": "Логи отправки",
            },
        ),
        migrations.AddField(
            model_name="mailing",
            name="sending_time",
            field=models.DateTimeField(
                blank=True, null=True, verbose_name="время отправки сообщения"
            ),
        ),
        migrations.AlterField(
            model_name="mailing",
            name="message",
            field=models.TextField(max_length=1024, verbose_name="сообщение"),
        ),
    ]
